# - name: Create project folder and virtual env
#   hosts: cpus
#   tasks:
#     - name: Create project folder
#       file:
#         path: ~/mlx
#         state: directory

#     - name: Create venv
#       shell: |
#         python3 -m venv ~/mlx/.venv

- name: Install docker
  hosts: cpus
  become: yes
  tasks:
    - name: Check connectivity
      ansible.builtin.ping:

    - name: Add Docker GPG key
      shell: |
        sudo apt-get update
        sudo apt-get install ca-certificates curl
        sudo install -m 0755 -d /etc/apt/keyrings
        sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
        sudo chmod a+r /etc/apt/keyrings/docker.asc

    - name: Add Docker repository
      shell: |
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
          $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
          sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get update

    - name: update apt list
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Install venv
      apt:
        name:
          - python3.12-venv
        state: present

    - name: Create venv
      shell: |
        python3 -m venv ~/mlx/.venv

    - name: Install docker-compose
      ansible.builtin.pip:
        name: docker-compose
        virtualenv: ~/mlx/.venv

- name: Pull Docker image and compose file
  hosts: cpus
  become: true
  tasks:
    - name: Fetch compose file from repo
      shell: |
        cd ~/mlx && curl -0 https://raw.githubusercontent.com/cnimmo16/mlx/main/search/docker-compose.yml > docker-compose.yml
    
    - name: Pull Docker image
      community.docker.docker_image:
        name: cameronnimmo/ml-search
        source: pull

- name: Run docker
  hosts: cpus
  become: true
  tasks:
    - name: Tear down existing services
      community.docker.docker_compose_v2:
        project_src: ~/mlx
        state: absent

    - name: Create and start services
      community.docker.docker_compose_v2:
        project_src: ~/mlx
      register: output

    - debug:
        var: output

    - name: Run `docker-compose up` again
      community.docker.docker_compose_v2:
        project_src: ~/mlx
        build: never
      register: output
